spring.application.name=rutaia
server.servlet.context-path=/rutaia/api/v1

# --- (MySQL) ---
spring.datasource.url=jdbc:mysql://localhost:3306/rutaia
spring.datasource.username=campus2023
spring.datasource.password=campus2023

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

n8n.webhook.consulta-url=https://earache-removable-gulp.ngrok-free.dev/webhook/rutaia-consulta

server.address: 0.0.0.0
port: 8080